Repository Yorichiiii22/hotel-Management-site-, pull requests merged in 2024-10, with the labels that each got.

#2 Resolved merge conflicts
  Project Food Menu/index.html
Labels: hacktoberfest, gssoc-ext

#5 solved the issues #3 and #4
  Project Food Menu/index.html
  Project Food Menu/style.css
Labels: hacktoberfest, gssoc-ext

#11 FIXED : footer Enhancement : Footer is not developed #6
  Project Food Menu/index.html
  Project Food Menu/restaurant.svg
  Project Food Menu/restaurant_logo.png
  Project Food Menu/style.css
  restaurant_logo.png
Labels: hacktoberfest, gssoc-ext

#13 #12 added the favicon
  Project Food Menu/Image src/favicon.png
  Project Food Menu/index.html
Labels: hacktoberfest, gssoc-ext

#17 Added Dark mode toggle
  Project Food Menu/index.html
  Project Food Menu/script.js
  Project Food Menu/style.css
Labels: hacktoberfest, gssoc-ext, level2, gssoc

#21 changed the color of font to enhance UI and visibility
  Project Food Menu/index.html
  Project Food Menu/style.css
Labels: enhancement, good first issue

#28 Added Restaurant Subscription Plans for Regular Users
  Project Food Menu/index.html
  Project Food Menu/style.css
Labels: hacktoberfest, gssoc-ext, hacktoberfest-accepted, gssoc
